# Copyright 2026 Bailey Beber and Soumalya Das
#
# Licensed under the Apache License, Version 2.0 (the "License")

"""
Theme engine for Void editor.
Supports full dark + light theme families with runtime switching.

CSS variables are exposed as $void-* to match void.py's CSS block.
"""

# ── Theme definitions ────────────────────────────────────────────────────────

THEMES = {
    # ── Tokyo Night family ──────────────────────────────────────────────────
    "tokyo-night": {
        "name": "Tokyo Night",
        "dark": True,
        "background":      "#1a1b2e",
        "background_alt":  "#16213e",
        "foreground":      "#c0caf5",
        "cursor":          "#c0caf5",
        "selection":       "#283457",
        "comment":         "#565f89",
        "red":             "#f7768e",
        "orange":          "#ff9e64",
        "yellow":          "#e0af68",
        "green":           "#9ece6a",
        "teal":            "#1abc9c",
        "blue":            "#7aa2f7",
        "purple":          "#bb9af7",
        "cyan":            "#7dcfff",
        "white":           "#c0caf5",
        "bright_black":    "#414868",
        "keyword_color":   "#bb9af7",
        "string_color":    "#9ece6a",
        "comment_color":   "#565f89",
        "number_color":    "#ff9e64",
        "function_color":  "#7aa2f7",
        "border_color":    "#414868",
        "status_bg":       "#16213e",
        "status_fg":       "#7aa2f7",
        "tab_active_bg":   "#1a1b2e",
        "tab_inactive_bg": "#16213e",
        "accent":          "#7aa2f7",
    },
    "tokyo-night-day": {
        "name": "Tokyo Night Day",
        "dark": False,
        "background":      "#e1e2ea",
        "background_alt":  "#d5d6de",
        "foreground":      "#3760bf",
        "cursor":          "#3760bf",
        "selection":       "#b6bfe2",
        "comment":         "#848cb5",
        "red":             "#f52a65",
        "orange":          "#b15c00",
        "yellow":          "#8c6c3e",
        "green":           "#587539",
        "teal":            "#007197",
        "blue":            "#2e7de9",
        "purple":          "#7847bd",
        "cyan":            "#007197",
        "white":           "#3760bf",
        "bright_black":    "#9699aa",
        "keyword_color":   "#7847bd",
        "string_color":    "#587539",
        "comment_color":   "#848cb5",
        "number_color":    "#b15c00",
        "function_color":  "#2e7de9",
        "border_color":    "#b6bfe2",
        "status_bg":       "#d5d6de",
        "status_fg":       "#2e7de9",
        "tab_active_bg":   "#e1e2ea",
        "tab_inactive_bg": "#d5d6de",
        "accent":          "#2e7de9",
    },

    # ── Dracula ──────────────────────────────────────────────────────────────
    "dracula": {
        "name": "Dracula",
        "dark": True,
        "background":      "#282a36",
        "background_alt":  "#1e1f29",
        "foreground":      "#f8f8f2",
        "cursor":          "#f8f8f2",
        "selection":       "#44475a",
        "comment":         "#6272a4",
        "red":             "#ff5555",
        "orange":          "#ffb86c",
        "yellow":          "#f1fa8c",
        "green":           "#50fa7b",
        "teal":            "#8be9fd",
        "blue":            "#6272a4",
        "purple":          "#bd93f9",
        "cyan":            "#8be9fd",
        "white":           "#f8f8f2",
        "bright_black":    "#44475a",
        "keyword_color":   "#ff79c6",
        "string_color":    "#f1fa8c",
        "comment_color":   "#6272a4",
        "number_color":    "#bd93f9",
        "function_color":  "#50fa7b",
        "border_color":    "#44475a",
        "status_bg":       "#1e1f29",
        "status_fg":       "#bd93f9",
        "tab_active_bg":   "#282a36",
        "tab_inactive_bg": "#1e1f29",
        "accent":          "#bd93f9",
    },

    # ── Nord family ──────────────────────────────────────────────────────────
    "nord": {
        "name": "Nord",
        "dark": True,
        "background":      "#2e3440",
        "background_alt":  "#262c36",
        "foreground":      "#d8dee9",
        "cursor":          "#d8dee9",
        "selection":       "#3b4252",
        "comment":         "#4c566a",
        "red":             "#bf616a",
        "orange":          "#d08770",
        "yellow":          "#ebcb8b",
        "green":           "#a3be8c",
        "teal":            "#8fbcbb",
        "blue":            "#81a1c1",
        "purple":          "#b48ead",
        "cyan":            "#88c0d0",
        "white":           "#eceff4",
        "bright_black":    "#4c566a",
        "keyword_color":   "#81a1c1",
        "string_color":    "#a3be8c",
        "comment_color":   "#4c566a",
        "number_color":    "#b48ead",
        "function_color":  "#88c0d0",
        "border_color":    "#4c566a",
        "status_bg":       "#262c36",
        "status_fg":       "#88c0d0",
        "tab_active_bg":   "#2e3440",
        "tab_inactive_bg": "#262c36",
        "accent":          "#88c0d0",
    },
    "nord-light": {
        "name": "Nord Light",
        "dark": False,
        "background":      "#eceff4",
        "background_alt":  "#e5e9f0",
        "foreground":      "#2e3440",
        "cursor":          "#2e3440",
        "selection":       "#d8dee9",
        "comment":         "#4c566a",
        "red":             "#bf616a",
        "orange":          "#d08770",
        "yellow":          "#ebcb8b",
        "green":           "#a3be8c",
        "teal":            "#8fbcbb",
        "blue":            "#5e81ac",
        "purple":          "#b48ead",
        "cyan":            "#88c0d0",
        "white":           "#eceff4",
        "bright_black":    "#9aa1ad",
        "keyword_color":   "#5e81ac",
        "string_color":    "#a3be8c",
        "comment_color":   "#4c566a",
        "number_color":    "#b48ead",
        "function_color":  "#88c0d0",
        "border_color":    "#d8dee9",
        "status_bg":       "#e5e9f0",
        "status_fg":       "#5e81ac",
        "tab_active_bg":   "#eceff4",
        "tab_inactive_bg": "#e5e9f0",
        "accent":          "#5e81ac",
    },

    # ── Gruvbox family ───────────────────────────────────────────────────────
    "gruvbox": {
        "name": "Gruvbox Dark",
        "dark": True,
        "background":      "#282828",
        "background_alt":  "#1d2021",
        "foreground":      "#ebdbb2",
        "cursor":          "#ebdbb2",
        "selection":       "#3c3836",
        "comment":         "#928374",
        "red":             "#cc241d",
        "orange":          "#d65d0e",
        "yellow":          "#d79921",
        "green":           "#98971a",
        "teal":            "#689d6a",
        "blue":            "#458588",
        "purple":          "#b16286",
        "cyan":            "#689d6a",
        "white":           "#ebdbb2",
        "bright_black":    "#504945",
        "keyword_color":   "#fb4934",
        "string_color":    "#b8bb26",
        "comment_color":   "#928374",
        "number_color":    "#d3869b",
        "function_color":  "#8ec07c",
        "border_color":    "#504945",
        "status_bg":       "#1d2021",
        "status_fg":       "#fabd2f",
        "tab_active_bg":   "#282828",
        "tab_inactive_bg": "#1d2021",
        "accent":          "#fabd2f",
    },
    "gruvbox-light": {
        "name": "Gruvbox Light",
        "dark": False,
        "background":      "#fbf1c7",
        "background_alt":  "#f2e5bc",
        "foreground":      "#3c3836",
        "cursor":          "#3c3836",
        "selection":       "#ebdbb2",
        "comment":         "#928374",
        "red":             "#9d0006",
        "orange":          "#af3a03",
        "yellow":          "#b57614",
        "green":           "#79740e",
        "teal":            "#427b58",
        "blue":            "#076678",
        "purple":          "#8f3f71",
        "cyan":            "#427b58",
        "white":           "#fbf1c7",
        "bright_black":    "#bdae93",
        "keyword_color":   "#9d0006",
        "string_color":    "#79740e",
        "comment_color":   "#928374",
        "number_color":    "#8f3f71",
        "function_color":  "#427b58",
        "border_color":    "#d5c4a1",
        "status_bg":       "#f2e5bc",
        "status_fg":       "#b57614",
        "tab_active_bg":   "#fbf1c7",
        "tab_inactive_bg": "#f2e5bc",
        "accent":          "#b57614",
    },

    # ── Catppuccin family ────────────────────────────────────────────────────
    "catppuccin": {
        "name": "Catppuccin Mocha",
        "dark": True,
        "background":      "#1e1e2e",
        "background_alt":  "#181825",
        "foreground":      "#cdd6f4",
        "cursor":          "#f5e0dc",
        "selection":       "#313244",
        "comment":         "#6c7086",
        "red":             "#f38ba8",
        "orange":          "#fab387",
        "yellow":          "#f9e2af",
        "green":           "#a6e3a1",
        "teal":            "#94e2d5",
        "blue":            "#89b4fa",
        "purple":          "#cba6f7",
        "cyan":            "#89dceb",
        "white":           "#cdd6f4",
        "bright_black":    "#45475a",
        "keyword_color":   "#cba6f7",
        "string_color":    "#a6e3a1",
        "comment_color":   "#6c7086",
        "number_color":    "#fab387",
        "function_color":  "#89b4fa",
        "border_color":    "#45475a",
        "status_bg":       "#181825",
        "status_fg":       "#89b4fa",
        "tab_active_bg":   "#1e1e2e",
        "tab_inactive_bg": "#181825",
        "accent":          "#89b4fa",
    },
    "catppuccin-macchiato": {
        "name": "Catppuccin Macchiato",
        "dark": True,
        "background":      "#24273a",
        "background_alt":  "#1e2030",
        "foreground":      "#cad3f5",
        "cursor":          "#f4dbd6",
        "selection":       "#363a4f",
        "comment":         "#6e738d",
        "red":             "#ed8796",
        "orange":          "#f5a97f",
        "yellow":          "#eed49f",
        "green":           "#a6da95",
        "teal":            "#8bd5ca",
        "blue":            "#8aadf4",
        "purple":          "#c6a0f6",
        "cyan":            "#91d7e3",
        "white":           "#cad3f5",
        "bright_black":    "#494d64",
        "keyword_color":   "#c6a0f6",
        "string_color":    "#a6da95",
        "comment_color":   "#6e738d",
        "number_color":    "#f5a97f",
        "function_color":  "#8aadf4",
        "border_color":    "#494d64",
        "status_bg":       "#1e2030",
        "status_fg":       "#8aadf4",
        "tab_active_bg":   "#24273a",
        "tab_inactive_bg": "#1e2030",
        "accent":          "#8aadf4",
    },
    "catppuccin-frappe": {
        "name": "Catppuccin Frappe",
        "dark": True,
        "background":      "#303446",
        "background_alt":  "#292c3c",
        "foreground":      "#c6d0f5",
        "cursor":          "#f2d5cf",
        "selection":       "#414559",
        "comment":         "#737994",
        "red":             "#e78284",
        "orange":          "#ef9f76",
        "yellow":          "#e5c890",
        "green":           "#a6d189",
        "teal":            "#81c8be",
        "blue":            "#8caaee",
        "purple":          "#ca9ee6",
        "cyan":            "#99d1db",
        "white":           "#c6d0f5",
        "bright_black":    "#51576d",
        "keyword_color":   "#ca9ee6",
        "string_color":    "#a6d189",
        "comment_color":   "#737994",
        "number_color":    "#ef9f76",
        "function_color":  "#8caaee",
        "border_color":    "#51576d",
        "status_bg":       "#292c3c",
        "status_fg":       "#8caaee",
        "tab_active_bg":   "#303446",
        "tab_inactive_bg": "#292c3c",
        "accent":          "#8caaee",
    },
    "catppuccin-latte": {
        "name": "Catppuccin Latte",
        "dark": False,
        "background":      "#eff1f5",
        "background_alt":  "#e6e9ef",
        "foreground":      "#4c4f69",
        "cursor":          "#dc8a78",
        "selection":       "#ccd0da",
        "comment":         "#8c8fa1",
        "red":             "#d20f39",
        "orange":          "#fe640b",
        "yellow":          "#df8e1d",
        "green":           "#40a02b",
        "teal":            "#179299",
        "blue":            "#1e66f5",
        "purple":          "#8839ef",
        "cyan":            "#04a5e5",
        "white":           "#eff1f5",
        "bright_black":    "#acb0be",
        "keyword_color":   "#8839ef",
        "string_color":    "#40a02b",
        "comment_color":   "#8c8fa1",
        "number_color":    "#fe640b",
        "function_color":  "#1e66f5",
        "border_color":    "#ccd0da",
        "status_bg":       "#e6e9ef",
        "status_fg":       "#1e66f5",
        "tab_active_bg":   "#eff1f5",
        "tab_inactive_bg": "#e6e9ef",
        "accent":          "#1e66f5",
    },

    # ── Solarized family ─────────────────────────────────────────────────────
    "solarized-dark": {
        "name": "Solarized Dark",
        "dark": True,
        "background":      "#002b36",
        "background_alt":  "#073642",
        "foreground":      "#839496",
        "cursor":          "#839496",
        "selection":       "#073642",
        "comment":         "#586e75",
        "red":             "#dc322f",
        "orange":          "#cb4b16",
        "yellow":          "#b58900",
        "green":           "#859900",
        "teal":            "#2aa198",
        "blue":            "#268bd2",
        "purple":          "#6c71c4",
        "cyan":            "#2aa198",
        "white":           "#eee8d5",
        "bright_black":    "#657b83",
        "keyword_color":   "#859900",
        "string_color":    "#2aa198",
        "comment_color":   "#586e75",
        "number_color":    "#6c71c4",
        "function_color":  "#268bd2",
        "border_color":    "#073642",
        "status_bg":       "#073642",
        "status_fg":       "#268bd2",
        "tab_active_bg":   "#002b36",
        "tab_inactive_bg": "#073642",
        "accent":          "#268bd2",
    },
    "solarized-light": {
        "name": "Solarized Light",
        "dark": False,
        "background":      "#fdf6e3",
        "background_alt":  "#eee8d5",
        "foreground":      "#657b83",
        "cursor":          "#657b83",
        "selection":       "#eee8d5",
        "comment":         "#93a1a1",
        "red":             "#dc322f",
        "orange":          "#cb4b16",
        "yellow":          "#b58900",
        "green":           "#859900",
        "teal":            "#2aa198",
        "blue":            "#268bd2",
        "purple":          "#6c71c4",
        "cyan":            "#2aa198",
        "white":           "#fdf6e3",
        "bright_black":    "#839496",
        "keyword_color":   "#859900",
        "string_color":    "#2aa198",
        "comment_color":   "#93a1a1",
        "number_color":    "#6c71c4",
        "function_color":  "#268bd2",
        "border_color":    "#eee8d5",
        "status_bg":       "#eee8d5",
        "status_fg":       "#268bd2",
        "tab_active_bg":   "#fdf6e3",
        "tab_inactive_bg": "#eee8d5",
        "accent":          "#268bd2",
    },

    # ── Material family ──────────────────────────────────────────────────────
    "material": {
        "name": "Material Ocean",
        "dark": True,
        "background":      "#0f111a",
        "background_alt":  "#090b10",
        "foreground":      "#8f93a2",
        "cursor":          "#80cbc4",
        "selection":       "#1f2233",
        "comment":         "#464b5d",
        "red":             "#f07178",
        "orange":          "#f78c6c",
        "yellow":          "#ffcb6b",
        "green":           "#c3e88d",
        "teal":            "#80cbc4",
        "blue":            "#82aaff",
        "purple":          "#c792ea",
        "cyan":            "#89ddff",
        "white":           "#eeffff",
        "bright_black":    "#464b5d",
        "keyword_color":   "#c792ea",
        "string_color":    "#c3e88d",
        "comment_color":   "#464b5d",
        "number_color":    "#f78c6c",
        "function_color":  "#82aaff",
        "border_color":    "#1f2233",
        "status_bg":       "#090b10",
        "status_fg":       "#82aaff",
        "tab_active_bg":   "#0f111a",
        "tab_inactive_bg": "#090b10",
        "accent":          "#82aaff",
    },
    "material-lighter": {
        "name": "Material Lighter",
        "dark": False,
        "background":      "#fafafa",
        "background_alt":  "#f5f5f5",
        "foreground":      "#546e7a",
        "cursor":          "#272727",
        "selection":       "#e7e7e7",
        "comment":         "#90a4ae",
        "red":             "#e53935",
        "orange":          "#f76d47",
        "yellow":          "#e2931d",
        "green":           "#91b859",
        "teal":            "#39adb5",
        "blue":            "#6182b8",
        "purple":          "#7c4dff",
        "cyan":            "#39adb5",
        "white":           "#fafafa",
        "bright_black":    "#cfd8dc",
        "keyword_color":   "#7c4dff",
        "string_color":    "#91b859",
        "comment_color":   "#90a4ae",
        "number_color":    "#f76d47",
        "function_color":  "#6182b8",
        "border_color":    "#e7e7e7",
        "status_bg":       "#f5f5f5",
        "status_fg":       "#6182b8",
        "tab_active_bg":   "#fafafa",
        "tab_inactive_bg": "#f5f5f5",
        "accent":          "#6182b8",
    },

    # ── Monokai ──────────────────────────────────────────────────────────────
    "monokai": {
        "name": "Monokai",
        "dark": True,
        "background":      "#272822",
        "background_alt":  "#1e1f1c",
        "foreground":      "#f8f8f2",
        "cursor":          "#f8f8f2",
        "selection":       "#49483e",
        "comment":         "#75715e",
        "red":             "#f92672",
        "orange":          "#fd971f",
        "yellow":          "#e6db74",
        "green":           "#a6e22e",
        "teal":            "#66d9e8",
        "blue":            "#66d9e8",
        "purple":          "#ae81ff",
        "cyan":            "#66d9e8",
        "white":           "#f8f8f2",
        "bright_black":    "#75715e",
        "keyword_color":   "#f92672",
        "string_color":    "#e6db74",
        "comment_color":   "#75715e",
        "number_color":    "#ae81ff",
        "function_color":  "#a6e22e",
        "border_color":    "#49483e",
        "status_bg":       "#1e1f1c",
        "status_fg":       "#a6e22e",
        "tab_active_bg":   "#272822",
        "tab_inactive_bg": "#1e1f1c",
        "accent":          "#a6e22e",
    },

    # ── One Dark ─────────────────────────────────────────────────────────────
    "one-dark": {
        "name": "One Dark",
        "dark": True,
        "background":      "#282c34",
        "background_alt":  "#21252b",
        "foreground":      "#abb2bf",
        "cursor":          "#528bff",
        "selection":       "#3e4451",
        "comment":         "#5c6370",
        "red":             "#e06c75",
        "orange":          "#d19a66",
        "yellow":          "#e5c07b",
        "green":           "#98c379",
        "teal":            "#56b6c2",
        "blue":            "#61afef",
        "purple":          "#c678dd",
        "cyan":            "#56b6c2",
        "white":           "#abb2bf",
        "bright_black":    "#4b5263",
        "keyword_color":   "#c678dd",
        "string_color":    "#98c379",
        "comment_color":   "#5c6370",
        "number_color":    "#d19a66",
        "function_color":  "#61afef",
        "border_color":    "#4b5263",
        "status_bg":       "#21252b",
        "status_fg":       "#61afef",
        "tab_active_bg":   "#282c34",
        "tab_inactive_bg": "#21252b",
        "accent":          "#61afef",
    },

    # ── Cyberpunk ────────────────────────────────────────────────────────────
    "cyberpunk": {
        "name": "Cyberpunk",
        "dark": True,
        "background":      "#0d0d0d",
        "background_alt":  "#0a0a0a",
        "foreground":      "#00ff41",
        "cursor":          "#ff0090",
        "selection":       "#1a1a2e",
        "comment":         "#4a4a6a",
        "red":             "#ff0000",
        "orange":          "#ff6600",
        "yellow":          "#ffff00",
        "green":           "#00ff41",
        "teal":            "#00ffff",
        "blue":            "#0080ff",
        "purple":          "#ff00ff",
        "cyan":            "#00ffff",
        "white":           "#ffffff",
        "bright_black":    "#333333",
        "keyword_color":   "#ff00ff",
        "string_color":    "#00ff41",
        "comment_color":   "#4a4a6a",
        "number_color":    "#ff6600",
        "function_color":  "#00ffff",
        "border_color":    "#ff0090",
        "status_bg":       "#0a0a0a",
        "status_fg":       "#ff0090",
        "tab_active_bg":   "#0d0d0d",
        "tab_inactive_bg": "#0a0a0a",
        "accent":          "#ff0090",
    },

    # ── Retro Terminal ───────────────────────────────────────────────────────
    "retro-terminal": {
        "name": "Retro Terminal",
        "dark": True,
        "background":      "#0c0c0c",
        "background_alt":  "#080808",
        "foreground":      "#33ff33",
        "cursor":          "#33ff33",
        "selection":       "#1a3d1a",
        "comment":         "#1a5c1a",
        "red":             "#ff3333",
        "orange":          "#ff8800",
        "yellow":          "#ffff33",
        "green":           "#33ff33",
        "teal":            "#33ffcc",
        "blue":            "#3333ff",
        "purple":          "#cc33ff",
        "cyan":            "#33ffff",
        "white":           "#ccffcc",
        "bright_black":    "#1a3d1a",
        "keyword_color":   "#33ffcc",
        "string_color":    "#ffff33",
        "comment_color":   "#1a5c1a",
        "number_color":    "#ff8800",
        "function_color":  "#33ff33",
        "border_color":    "#1a5c1a",
        "status_bg":       "#080808",
        "status_fg":       "#33ff33",
        "tab_active_bg":   "#0c0c0c",
        "tab_inactive_bg": "#080808",
        "accent":          "#33ff33",
    },

    # ── Minimalist (light) ───────────────────────────────────────────────────
    "minimalist": {
        "name": "Minimalist Light",
        "dark": False,
        "background":      "#ffffff",
        "background_alt":  "#f5f5f5",
        "foreground":      "#333333",
        "cursor":          "#333333",
        "selection":       "#e0e0e0",
        "comment":         "#999999",
        "red":             "#d32f2f",
        "orange":          "#e64a19",
        "yellow":          "#f9a825",
        "green":           "#388e3c",
        "teal":            "#00796b",
        "blue":            "#1976d2",
        "purple":          "#7b1fa2",
        "cyan":            "#0097a7",
        "white":           "#ffffff",
        "bright_black":    "#bdbdbd",
        "keyword_color":   "#7b1fa2",
        "string_color":    "#388e3c",
        "comment_color":   "#999999",
        "number_color":    "#e64a19",
        "function_color":  "#1976d2",
        "border_color":    "#e0e0e0",
        "status_bg":       "#f5f5f5",
        "status_fg":       "#1976d2",
        "tab_active_bg":   "#ffffff",
        "tab_inactive_bg": "#f5f5f5",
        "accent":          "#1976d2",
    },

    # ── Nature ───────────────────────────────────────────────────────────────
    "nature": {
        "name": "Nature",
        "dark": True,
        "background":      "#1a2316",
        "background_alt":  "#141c10",
        "foreground":      "#c8d8b0",
        "cursor":          "#8bc34a",
        "selection":       "#2d3d28",
        "comment":         "#5a7050",
        "red":             "#e57373",
        "orange":          "#ffb74d",
        "yellow":          "#fff176",
        "green":           "#8bc34a",
        "teal":            "#4db6ac",
        "blue":            "#64b5f6",
        "purple":          "#ba68c8",
        "cyan":            "#4dd0e1",
        "white":           "#c8d8b0",
        "bright_black":    "#3d5236",
        "keyword_color":   "#8bc34a",
        "string_color":    "#fff176",
        "comment_color":   "#5a7050",
        "number_color":    "#ffb74d",
        "function_color":  "#4dd0e1",
        "border_color":    "#3d5236",
        "status_bg":       "#141c10",
        "status_fg":       "#8bc34a",
        "tab_active_bg":   "#1a2316",
        "tab_inactive_bg": "#141c10",
        "accent":          "#8bc34a",
    },

    # ── One Light ────────────────────────────────────────────────────────────
    "one-light": {
        "name": "One Light",
        "dark": False,
        "background":      "#fafafa",
        "background_alt":  "#f0f0f0",
        "foreground":      "#383a42",
        "cursor":          "#526fff",
        "selection":       "#e5e5e6",
        "comment":         "#a0a1a7",
        "red":             "#e45649",
        "orange":          "#986801",
        "yellow":          "#c18401",
        "green":           "#50a14f",
        "teal":            "#0184bc",
        "blue":            "#4078f2",
        "purple":          "#a626a4",
        "cyan":            "#0997b3",
        "white":           "#fafafa",
        "bright_black":    "#c8c8c8",
        "keyword_color":   "#a626a4",
        "string_color":    "#50a14f",
        "comment_color":   "#a0a1a7",
        "number_color":    "#986801",
        "function_color":  "#4078f2",
        "border_color":    "#e5e5e6",
        "status_bg":       "#f0f0f0",
        "status_fg":       "#4078f2",
        "tab_active_bg":   "#fafafa",
        "tab_inactive_bg": "#f0f0f0",
        "accent":          "#4078f2",
    },

    # ── GitHub Light ─────────────────────────────────────────────────────────
    "github-light": {
        "name": "GitHub Light",
        "dark": False,
        "background":      "#ffffff",
        "background_alt":  "#f6f8fa",
        "foreground":      "#24292e",
        "cursor":          "#0366d6",
        "selection":       "#c8e1ff",
        "comment":         "#6a737d",
        "red":             "#d73a49",
        "orange":          "#e36209",
        "yellow":          "#b08800",
        "green":           "#22863a",
        "teal":            "#032f62",
        "blue":            "#0366d6",
        "purple":          "#6f42c1",
        "cyan":            "#1b7c83",
        "white":           "#ffffff",
        "bright_black":    "#d1d5da",
        "keyword_color":   "#d73a49",
        "string_color":    "#032f62",
        "comment_color":   "#6a737d",
        "number_color":    "#005cc5",
        "function_color":  "#6f42c1",
        "border_color":    "#e1e4e8",
        "status_bg":       "#f6f8fa",
        "status_fg":       "#0366d6",
        "tab_active_bg":   "#ffffff",
        "tab_inactive_bg": "#f6f8fa",
        "accent":          "#0366d6",
    },

    # ── PaperColor Light ─────────────────────────────────────────────────────
    "papercolor-light": {
        "name": "PaperColor Light",
        "dark": False,
        "background":      "#eeeeee",
        "background_alt":  "#e4e4e4",
        "foreground":      "#444444",
        "cursor":          "#0087af",
        "selection":       "#d7d7d7",
        "comment":         "#878787",
        "red":             "#af0000",
        "orange":          "#d75f00",
        "yellow":          "#5f8700",
        "green":           "#008700",
        "teal":            "#005f87",
        "blue":            "#0087af",
        "purple":          "#8700af",
        "cyan":            "#005f87",
        "white":           "#eeeeee",
        "bright_black":    "#bcbcbc",
        "keyword_color":   "#af0000",
        "string_color":    "#008700",
        "comment_color":   "#878787",
        "number_color":    "#8700af",
        "function_color":  "#0087af",
        "border_color":    "#d0d0d0",
        "status_bg":       "#e4e4e4",
        "status_fg":       "#0087af",
        "tab_active_bg":   "#eeeeee",
        "tab_inactive_bg": "#e4e4e4",
        "accent":          "#0087af",
    },

    # ── Ayu Light ────────────────────────────────────────────────────────────
    "ayu-light": {
        "name": "Ayu Light",
        "dark": False,
        "background":      "#fafafa",
        "background_alt":  "#f3f3f3",
        "foreground":      "#575f66",
        "cursor":          "#ff9940",
        "selection":       "#d1e4f4",
        "comment":         "#abb0b6",
        "red":             "#f07171",
        "orange":          "#fa8d3e",
        "yellow":          "#f2ae49",
        "green":           "#86b300",
        "teal":            "#4cbf99",
        "blue":            "#36a3d9",
        "purple":          "#a37acc",
        "cyan":            "#4cbf99",
        "white":           "#fafafa",
        "bright_black":    "#d9d8d7",
        "keyword_color":   "#fa8d3e",
        "string_color":    "#86b300",
        "comment_color":   "#abb0b6",
        "number_color":    "#a37acc",
        "function_color":  "#36a3d9",
        "border_color":    "#e8e8e8",
        "status_bg":       "#f3f3f3",
        "status_fg":       "#ff9940",
        "tab_active_bg":   "#fafafa",
        "tab_inactive_bg": "#f3f3f3",
        "accent":          "#ff9940",
    },

    # ── Rosé Pine Dawn ───────────────────────────────────────────────────────
    "rose-pine-dawn": {
        "name": "Rose Pine Dawn",
        "dark": False,
        "background":      "#faf4ed",
        "background_alt":  "#fffaf3",
        "foreground":      "#575279",
        "cursor":          "#286983",
        "selection":       "#dfdad9",
        "comment":         "#9893a5",
        "red":             "#b4637a",
        "orange":          "#ea9d34",
        "yellow":          "#d7827a",
        "green":           "#56949f",
        "teal":            "#286983",
        "blue":            "#286983",
        "purple":          "#907aa9",
        "cyan":            "#56949f",
        "white":           "#faf4ed",
        "bright_black":    "#cecacd",
        "keyword_color":   "#b4637a",
        "string_color":    "#56949f",
        "comment_color":   "#9893a5",
        "number_color":    "#ea9d34",
        "function_color":  "#286983",
        "border_color":    "#dfdad9",
        "status_bg":       "#fffaf3",
        "status_fg":       "#286983",
        "tab_active_bg":   "#faf4ed",
        "tab_inactive_bg": "#fffaf3",
        "accent":          "#907aa9",
    },

    # ── Everforest Light ─────────────────────────────────────────────────────
    "everforest-light": {
        "name": "Everforest Light",
        "dark": False,
        "background":      "#fff9f0",
        "background_alt":  "#f4ede3",
        "foreground":      "#5c6a72",
        "cursor":          "#3a94c5",
        "selection":       "#e8e2d4",
        "comment":         "#939f91",
        "red":             "#f85552",
        "orange":          "#f57d26",
        "yellow":          "#dfa000",
        "green":           "#8da101",
        "teal":            "#35a77c",
        "blue":            "#3a94c5",
        "purple":          "#df69ba",
        "cyan":            "#089894",
        "white":           "#fff9f0",
        "bright_black":    "#d8cabc",
        "keyword_color":   "#f85552",
        "string_color":    "#8da101",
        "comment_color":   "#939f91",
        "number_color":    "#df69ba",
        "function_color":  "#3a94c5",
        "border_color":    "#e8e2d4",
        "status_bg":       "#f4ede3",
        "status_fg":       "#8da101",
        "tab_active_bg":   "#fff9f0",
        "tab_inactive_bg": "#f4ede3",
        "accent":          "#35a77c",
    },

    # ── Kanagawa Lotus ───────────────────────────────────────────────────────
    "kanagawa-lotus": {
        "name": "Kanagawa Lotus",
        "dark": False,
        "background":      "#f2ecbc",
        "background_alt":  "#e7dba0",
        "foreground":      "#545464",
        "cursor":          "#43436c",
        "selection":       "#c9cbd1",
        "comment":         "#8a8980",
        "red":             "#c84053",
        "orange":          "#cc6d00",
        "yellow":          "#77713f",
        "green":           "#6f894e",
        "teal":            "#597b75",
        "blue":            "#4d699b",
        "purple":          "#624c83",
        "cyan":            "#4e8ca2",
        "white":           "#f2ecbc",
        "bright_black":    "#c5c9c5",
        "keyword_color":   "#c84053",
        "string_color":    "#6f894e",
        "comment_color":   "#8a8980",
        "number_color":    "#cc6d00",
        "function_color":  "#4d699b",
        "border_color":    "#c9cbd1",
        "status_bg":       "#e7dba0",
        "status_fg":       "#4d699b",
        "tab_active_bg":   "#f2ecbc",
        "tab_inactive_bg": "#e7dba0",
        "accent":          "#624c83",
    },
}

# ── Theme categorisation ─────────────────────────────────────────────────────

DARK_THEMES:  list[str] = [k for k, v in THEMES.items() if v.get("dark", True)]
LIGHT_THEMES: list[str] = [k for k, v in THEMES.items() if not v.get("dark", True)]
THEME_NAMES:  list[str] = list(THEMES.keys())


# ── Accessors ────────────────────────────────────────────────────────────────

def get_theme(name: str) -> dict:
    """Return the theme dict for *name*, falling back to tokyo-night."""
    return THEMES.get(name, THEMES["tokyo-night"])


def theme_css_variables(theme: dict) -> dict[str, str]:
    """
    Return a mapping of Textual CSS variable names -> hex color values.
    Keys match the $void-* variables used in void.py's App.CSS block.
    Called by VoidApp.get_css_variables() and indirectly by refresh_css().
    """
    return {
        "void-bg":           theme["background"],
        "void-bg-alt":       theme["background_alt"],
        "void-fg":           theme["foreground"],
        "void-cursor":       theme["cursor"],
        "void-selection":    theme["selection"],
        "void-comment":      theme["comment"],
        "void-accent":       theme.get("accent", theme["blue"]),
        "void-keyword":      theme["keyword_color"],
        "void-string":       theme["string_color"],
        "void-number":       theme["number_color"],
        "void-function":     theme["function_color"],
        "void-border":       theme["border_color"],
        "void-status-bg":    theme["status_bg"],
        "void-status-fg":    theme["status_fg"],
        "void-tab-active":   theme["tab_active_bg"],
        "void-tab-inactive": theme["tab_inactive_bg"],
    }


# ── Legacy helper (kept for backward compatibility) ──────────────────────────

def get_css_for_theme(theme: dict) -> str:
    """Generate Textual CSS variable block (legacy, prefer theme_css_variables)."""
    v = theme_css_variables(theme)
    return "\n".join(f"${k}: {val};" for k, val in v.items())
